const newObject = {
  title: "Welcome to randomQuotes API",
  description:
    "Random Quotes Adalah Sekumpulan Kata Tersimpan Yang Dimuat Secara Acak, Dibuat Menggunakan ExpressJS",
  endpoint: {
    quote: "[GET] /api/quote",
    katabijak: "[GET] /api/katabijak",
  },
  parameter: "tidak ada parameter yang diperlukan.",
};

const quotes = [
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Innovation distinguishes between a leader and a follower. - Steve Jobs",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "When there is a will, there is way",
  "The right chair for the right person",
  "Time is what we want most and what we use worst",
  "Happiness is not something readymade. It comes from your own actions",
  "You can either experience the pain of discipline or the pain of regret. The choice is yours",
  "Do something today that your future self will thank you for",
  "Take the risk or lose the chance",
  "Success is going from failure to failure without losing your enthusiasm",
  "Learn from the mistakes of others. You cannot live long enough to do all the fault itself",
  "Our greatest pride is not never fail, but bounced back every time we fall",
  "Impossible is just an opinion",
  "A negative mind will never give you a positive life",
  "Don’t stop when you are tired. Stop when you are done",
  "The absence of faith that makes people afraid to face challenges",
  "Life is inherently risky. There is only one big risk you should avoid at all costs, and that is the risk of doing nothing",
  "We make a living by what we get, but we make a life by what we give",
  "Life is the art of drawing without an eraser",
  "Action speaks louder than words",
  "Pain can change you, but that doesn't mean it has to be a bad change. Take that pain and turn it into wisdom",
  "Do you know the difference between education and experience? Education is when you read the fine print; experience is what you get when you don't",
];

const kataBijak = [
  "Bermimpilah yang besar dan selalu berani untuk gagal.",
  "Belajarlah dari hari hari kemarin dan hiduplah untuk hari ini, lalu berharaplah untuk hari esok.",
  "Kesulitan yang sebenarnya ialah mengatasi caramu berpikir mengenai diri kamu sendiri.",
  "Tidak perlu menjadi seseorang yang serba bisa, tekuni saja salah satu bidang yang paling kamu suka, kemudian jadilah seseorang yang hebat dengan bidang tersebut.",
  "Tidak ada kata tidak mungkin, sebelum kamu sempat mencobanya.",
  "Jangan pernah takut menghadapi masa depan, hadapi lalu perjuangkanlah masa depan itu.",
  "Apabila kamu mampu memimpikannya, maka kamu juga bisa melakukannya.",
  "Ingatlah bahwa hari ini hanyalah hari yang buruk dan bukan kehidupan yang buruk.",
  "Jangan pernah menyesali masa lalu yang pernah terjadi sebelumnya, tetapi belajarlah dari masa lalu tersebut.",
  "Ada begitu banyak cara agar kamu bisa maju, akan tetapi hanya ada satu cara untuk tetap diam.",
  "Jangan pernah berharap bahwa jalan hidupmu akan seperti jalan hidup orang lain. Perjalanan hidup yang kamu miliki merupakan sesuatu yang unik, seperti dirimu.",
  "Fokuslah untuk mencapai tujuanmu, meskipun banyak hal yang menarik dalam perjalanannya.",
  "Tidak peduli bagaimana kerasnya kehidupan yang kamu miliki di masa lalu, kamu selalu bisa memulainya kembali.",
  "Impian tidak dapat terwujud dengan sendirinya, akan tetapi impian akan datang ketika seseorang berusaha untuk meraihnya.",
  "Perjalanan akan menjadi jauh lebih muda, apabila kamu tidak membawa masa lalumu.",
  "Berjalanlah jangan berlari, karena hidup adalah perjalanan dan bukannya pelarian.",
  "Jangan khawatir, seluruh upaya yang kamu lakukan akan berbuah manis. Berusaha saja yang kuat dan berdoa pula yang kuat.",
  "Jangan hanya terus bermalas-malasan setiap hati, jadikan hidup kamu jadi lebih bermakna dengan bekerja lebih giat.",
  "Hidup bukan hanya mengenai mendapatkan serta memiliki belaka, akan tetapi juga mengenai memberi serta menjadi sesuatu.",
  "Nikmatilah hal-hal kecil yang ada dalam hidup, sebab suatu hari nanti kamu akan melihat ke belakang dan kemudian menyadari bahwa itu adalah hal-hal besar.",
  "Kemana pun diri kamu pergi, lakukanlah segala sesuatu dengan segenap hati.",
  "Keberhasilan dalam hidup, hanya mampu didapatkan ketika seseorang mau berjuang dengan keras untuk mendapatkannya.",
  "Kamu memiliki waktu terbatas, sehingga jangan sia-siakan waktu itu untuk menjalani kehidupan orang lain.",
  "Setiap orang memiliki jatahnya masing-masing untuk gagal. Maka habiskanlah jatah kegagalanmu ketika kamu masih muda.",
  "Mulailah dari mana kamu berada. Gunakanlah segala sesuatu yang kamu miliki. Lakukanlah apa saja yang kamu bisa.",
  "Bersiaplah dalam kesunyian dan biarkan kesuksesan yang membuat hidupmu menjadi bising.",
  "Ketika kita masih diberikan kesempatan untuk bangun di pagi hari, itu artinya Tuhan masih memberikan kesempatan pada kita untuk melakukan pekerjaan yang harus kita lakukan.",
  "Kita adalah apa yang kita kerjakan secara berulang kali. Oleh karena itu, keunggulan bukanlah suatu hal perbuatan melainkan suatu kebiasaan.",
  "Hidup merupakan sebuah pertanyaan serta bagaimana manusia menjalani kehidupan merupakan jawabannya.",
  "Hidup itu membutuhkan suatu perjuangan, sebab tidak ada satu hal pun yang mampu sukses tanpa adanya perjuangan di dalamnya.",
  "Banyak orang yang takut gagal, sehingga mereka akhirnya tidak bertindak. Padahal tidak bertindak merupakan suatu kegagalan yang jelas telah terjadi.",
  "Doronglah diri kamu sendiri, sebab tidak ada orang lain yang akan melakukan hal itu untuk dirimu.",
  "Jangan pernah berhenti ketika kamu lelah, berhentilah ketika kamu telah selesai.",
  "Bertindak merupakan kunci yang dasar untuk seluruh kesuksesan yang ingin kamu raih.",
  "Kemuliaan yang paling besar dalam hidupa tidak terletak pada ketangguhan yang dimiliki seseorang, akan tetapi dalam bangkit setiap kali ia terjatuh.",
  "Kamu tidak dilahirkan untuk menjadi sosok yang sempurna, akan tetapi untuk menjadi dirimu yang apa adanya.",
  "Jangan pernah katakan tidak mungkin, akan tetapi katakan saja bagaimana caranya.",
  "Apabila kamu tengah mencari seseorang yang mampu mengubah hidupmu, maka lihatlah ke cermin.",
  "Milikilah keyakinan yang tidak akan tergoyahkan akan diri kamu sendiri untuk menjadi sosok yang selalu kamu inginkan.",
  "Kamu adalah wujud kesuksesan yang sejati, sehingga ketika kamu dapat mempercayai diri sendiri, maka cintailah diri sendiri dan tetap menjadi diri sendiri.",
  "Ketika ada seseorang mengatakan bahwa kamu telah berubah, sebenarnya itu hanyalah karena kamu berhenti melakukan apa yang mereka ingin kamu lakukan.",
  "Jangan pernah membuat suatu keputusan yang permanen hanya untuk perasaan yang sementara waktu.",
  "Berani dalam mengambil keputusan, maka kamu telah melangkah sepuluh kali lebih cepat menuju kesuksesan.",
  "Realitas kehidupan yang kamu miliki ialah deskripsi mengenai jiwa serta pikiran kamu.",
  "Setiap mimpi yang besar dimulai dengan seorang pemimpi. Ingatlah selalu bahwa kamu memiliki kesabaran, kekuatan serta hasrat untuk meraih segala bintang yang dapat mengubah dunia.",
  "Mereka bilang bahwa impian yang saya miliki terlalu besar, akan tetapi saya bilang bahwa cara mereka berpikir yang terlalu kecil.",
  "Usai kamu mengganti pikiran-pikiran negatif dengan pikiran positif, maka kamu pun akan mulai mendapatkan hasil yang positif.",
  "Beranilah untuk mengambil risiko, sebab tidak ada yang mampu menggantikan pengalaman.",
  "Kegagalan hanya dibuat oleh mereka yang telah gagal menjadi sosok yang berani dan bukan oleh mereka yang berani untuk gagal.",
  "Hanya ada satu hal yang mampu membuat mimpi tidak tercapai, yaitu adalah ketakutan akan kegagalan.",
  "Prestasi tidak dapat diraih tanpa adanya semangat.",
  "Jangan pernah merasa khawatir tentang kegagalan, akan tetapi khawatirlah tentang peluang yang telah kamu lewatkan ketika kamu tidak mencoba untuk melakukan sesuatu.",
  "Jangan takut dengan ketakutanmu. Mereka tidak ada di sana untuk membuat dirimu takut. Mereka ada di sana untuk memberi tahu, bahwa ada suatu hal yang berharga untuk dirimu.",
  "Bermimpilah dalam hidup dan jangan hidup dalam mimpi -Andrea Hirata.",
  "Ketika kamu melakukan sesuatu yang mulia serta indah akan tetapi tidak ada satu orang pun yang memerhatikan, maka jangan merasa sedih. Sebab matahari pun mampu tampil cantik setiap pagi hari meskipun sebagian besar penontonnya masih tertidur. – John Lennon.",
];

module.exports = {
  quotes,
  kataBijak,
  newObject,
};
